name: Release

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  PROJECT_NAME: color_difference

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust:
          - stable
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
      
      - name: Build sources
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME }}
          path: target/release/${{ env.PROJECT_NAME }}