name: Release

on:
  push:
    branches:
      - main

env:
  ACTIONS_STEP_DEBUG: true
  PROJECT_NAME: color_difference

jobs:
  linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust:
          - stable

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build sources
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      # - name: Run UPX
      #   uses: crazy-max/ghaction-upx@v1
      #   with:
      #     version: latest
      #     files: target/release/${{ env.PROJECT_NAME }}
      #     args: --brute

      - name: Rename file
        run: cp target/release/${{ env.PROJECT_NAME }} x86_64-unknown-linux-gnu

      - name: Release with artifacts
        uses: ncipollo/release-action@v1
        with:
          name: Release
          tag: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}
          artifacts: x86_64-unknown-linux-gnu