name: Release

on:
  push:
    branches:
      - main

env:
  ACTIONS_STEP_DEBUG: true
  PROJECT_NAME: color_difference

jobs:
  linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust:
          - stable

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Output version
        id: version_step
        run: |
          export VERSION="$(grep -oP '# color_difference\K.*' README.md | xargs)" &&
            echo "::set-output name=version_output::$VERSION"

    outputs:
      version_output: ${{ steps.version_step.outputs.version_output }}

  release:
    needs: [linux]

    runs-on: ubuntu-latest

    steps:
      - name: Test version number
        run: echo "${{ needs.linux.version_step.outputs.version_output }}""