name: Release

on:
  push:
    branches:
      - main

env:
  ACTIONS_STEP_DEBUG: true
  PROJECT_NAME: color_difference

jobs:
  linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust:
          - stable

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set version output
        id: version_step
        run: echo "::set-output name=version::$(grep -oP '# color_difference\K.*' README.md | xargs)"

    outputs:
      version: ${{ steps.version_step.outputs.version }}

  release:
    needs: [linux]

    runs-on: ubuntu-latest

    steps:
      - name: Test version number
        run: echo "${{ needs.linux.version_step.outputs.version }}"